[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "paris"
# bytecode_hash = "none"
# cbor_metadata = false

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
